add 5 laba
Maryan27/Repositoryy pull request #1
Opened 2023-11-26 17:46 UTC by Maryan27

added the file of the 5th laboratory

2023-11-30 10:34 UTC, EgorkaKv requested changes

2023-11-30 10:34 UTC, EgorkaKv commented on лабаа(5).py
> +    def __init__(self, brand, size, color, price, quantity, material, numberOfSales):
Забагато аргументів (Макс 5 шт)

2023-11-30 10:34 UTC, EgorkaKv commented on лабаа(5).py
> +    def top_sneakers(self, n=5):
Незрозуміло що робить метод

2023-11-30 10:34 UTC, EgorkaKv commented on лабаа(5).py
> +if __name__ == __main__
Неправильно реалізований метод маін

2023-12-03 17:48 UTC, EgorkaKv requested changes

2023-12-03 17:48 UTC, EgorkaKv commented on лабаа(5).py
> +        self.material = material
Фатальна помилка, зімнної material не існує

2023-12-03 17:48 UTC, EgorkaKv commented on лабаа(5).py
> +    def top_sneakers(self, n=5):
Що означає магічне число 5?

2023-12-03 17:48 UTC, EgorkaKv commented on лабаа(5).py
> +    for sneaker in top_sneakers:
Фатальна помилка. Незавершений цикл

2023-12-03 17:48 UTC, EgorkaKv commented on лабаа(5).py
> +if __name__ == "__main__"
Немає двокрапки після умови

2023-12-03 17:48 UTC, EgorkaKv commented on лабаа(5).py
> +
параметри починаючи з 4го передаються в трубу

2023-12-03 17:48 UTC, EgorkaKv commented on лабаа(5).py
> +    (main)
Невірний синтаксис визову метода

2023-12-03 17:48 UTC, EgorkaKv commented on лабаа(5).py
> +    def top_sneakers(self, n=5):
Додай коментар для пояснення роботи коду

2023-12-03 17:48 UTC, EgorkaKv commented on лабаа(5).py
> +
мають бути 2 пусті строки після функції

2023-12-03 18:30 UTC, Maryan27 commented on лабаа(5).py
> +        self.material = material
виправив помилку

2023-12-03 18:31 UTC, Maryan27 commented on лабаа(5).py
> +    (main)
виправив помилку

2023-12-03 18:32 UTC, Maryan27 commented on лабаа(5).py
> +if __name__ == __main__
виправив помилку

2023-12-03 18:32 UTC, Maryan27 commented on лабаа(5).py
> +    def __init__(self, brand, size, color, price, quantity, material, numberOfSales):
виправив помилку

2023-12-04 07:21 UTC, closed without merging